In [10]:
import numpy as np

def create_table(n):
    table = np.zeros((n, n), dtype=int)  # create a n x n array of zeros
    middle = n // 2  # get the index of the middle element
    table[middle, middle] = 9  # set the middle element to 9
    table[0, :] = 1  # set the first row to ones
    table[-1, :] = 1  # set the last row to ones
    table[:, 0] = 1  # set the first column to ones
    table[:, -1] = 1  # set the last column to ones
    return table

table = create_table(5)

print(table)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [8]:
np.binary_repr

<function numpy.binary_repr(num, width=None)>

In [17]:
1//2

0